### PR TITLE
allow the lazy loading of images without a class attribute

### PR DESCRIPTION
**Pull request by 2ndkauboy**
With the current regex, only images from the media library will be lazy loaded. A alightly modified regex would enable all images to be lazy loaded.

### CODE REVIEW

**Review by bueltge — APPROVED** [review]

**Comment by 2ndkauboy** [comment]
@bueltge I tested the current regex with images from Gutenberg and it would not match the img tags. This regex works with quite complex img tags on my blog, both with Gutenberg posts and regular posts (including lots of data attributes).

**Comment by bueltge** [comment]
@2ndkauboy will you add more tests so that you validate the PR to a solid change?

**Comment by 2ndkauboy** [comment]
Unfortunately we current don't have any tests in Crazy-Lazy.

**Comment by bueltge** [comment]
Yes I know. I mean also locally tests to merge this topic. However it would be fine that we get tests.

**Pull request merged**
