### PR TITLE
Add support for text and html widget

### LINKED ISSUE #20: Add support for (media) widgets
If I am correct Crazy Lazy just supports post content and post thumbnails:
https://github.com/pluginkollektiv/crazy-lazy/blob/2c265e16ccb9580bcc273a0a3dc8f4cf022c77a1/inc/crazy-lazy.class.php#L41-L56

Let's add support for (media) widgets.

We could use `widget_text`and `widget_{$this->id_base}_instance`(but I have no clue how the latter works ...)

### PR DESCRIPTION
**Pull request by florianbrinkmann**
Does not work for galleries in html widgets, because there is no filter in the `widget()` method after the gallery shortcode is parsed.

It’s not possible to add lazy loading for media widgets (image and gallery) at the moment, because there is no filter for the `wp_get_attachment_image()` output (https://core.trac.wordpress.org/ticket/27399).

Fixes #20.

### CODE REVIEW

**Review by bueltge — APPROVED** [review]

**Comment by 2ndkauboy** [comment]
@florianbrinkmann could you resolve the conflict so we can merge this PR?

**Comment by florianbrinkmann** [comment]
@2ndkauboy yes, would like to do that, but I don’t know how 😇 I see the resolve conflicts option, but I would need write access to the repo do use it. Is there another way that I can see what the conflict is or could I get write access to the repo?

**Comment by 2ndkauboy** [comment]
Only very few conflicts can be solved on GitHub. To solve, just fetch the latest cajnges from origin/master and merge or rebase your branch on it. Then push (or force push, if you did a rebase) and the PR should be ready to be merged.

**Comment by 2ndkauboy** [comment]
Or just watch my talk from WordCamp Würzburg starting around minute 18:00, where I explain how to resolve a conflict: https://wordpress.tv/2018/09/24/bernhard-kau-git-qa/

**Comment by florianbrinkmann** [comment]
Will do that, thanks for the link!

**Comment by florianbrinkmann** [comment]
WIll close that and create a new one, seems easier for the moment for me :D

**Pull request closed without merging**
