### PR TITLE
improved regex and added data attribute to skip lazy loading

### LINKED ISSUE #9: Images not shown
It´s me again. Different pictures in Posts not showing now when I activate the plugin. Example: http://hansert-innenarchitektur.de/2015/08/10/tunnel-2/ 

The picture:

<a href="http://hansert-innenarchitektur.de/wp-content/uploads/2015/08/GDA16_HO_NOMINEE_1C-Kopie1.png">GDA16_HO_NOMINEE_1C Kopie</a>

doesn`t show when I activate the plugin.

Also all pictures on this page: http://hansert-innenarchitektur.de/portfolio/

Can't keep the Plugin activated - sorry!

Frontpage is fine!

### LINKED ISSUE #11: Feature request: disabling crazy-lazy for specific images
It would be great to disable crazy-lazy effect for specific images with an extra CSS class.

Maybe with an extra css class like this example: 

```
<img src="http://www.domain.tld/images/2.jpg" class="skip_crazylazy"/>
```

Within my theme files I can add this class to e.g. the logo and crazy-lazy is not loading my logo with the lazy load effect.

Thank you! ;-)

### PR DESCRIPTION
**Pull request by 2ndkauboy**
-  only one regex and replacement in a callback funtion
- commenting regex for easier debugging on further bugs or feature requests
- check in the callback function the attribute "data-crazy-lazy" for "skip"
  
  Closes #9 and #11.

### CODE REVIEW

**Comment by 2ndkauboy** [comment]
I think this PR will not only fix the feature request #11 but also improves the general stability of the regex a lot. The only drawback of my current solution: as I am using a closure, it requires PHP 5.3+ to run. Should be use an implementation without the need for PHP 5.3+ or do you think that's OK?

**Comment by Zodiac1978** [comment]
I'm fine with requiring PHP 5.3.

**Comment by 2ndkauboy** [comment]
I'd also like to have opinions on the "skip attribute". I should definetly not be a class attribute value. It could be one of the following (I implemented the last variant):

`data-crazy-lazy-skip`
`data-crazy-lazy-skip="true"`
`data-crazy-lazy="skip"`

**Comment by swissspidy** [comment]
If it's not difficult to maintain back compat, then why not leave it like this? There's no need for a closure here, nor any benefit you get from it.

I don't have a problem with requiring PHP 5.3 (if it's done [properly](https://github.com/wearerequired/wp-requirements-check)) in general.

**Comment by Zodiac1978** [comment]
Will this fix #9 too?

**Comment by 2ndkauboy** [comment]
This might also fix the other issue, but as we don't have some HTML source code to test it, we should ask @philliproth to try it again.

**Comment by 2ndkauboy** [comment]
Regarding PHP 5.2 support. It's possible without an anonymous function but it would be rather ugly :)

**Comment by Zodiac1978** [comment]
> This might also fix the other issue, but as we don't have some HTML source code to test it, we should ask @philliproth to try it again.

He provided already some code https://www.philliproth.de/crazy.txt

**Comment by 2ndkauboy** [comment]
Sorry, I somehow haven't seen the link. Yes, the new regex works on the example code and should correcty replace the img tag.

**Comment by 2ndkauboy** [comment]
I want to merge that today and make a new release before WP 4.6 will be out tomorrow. Any thoughts on the "skip attribute"? Or is the current version OK with you?

**Pull request merged**
